// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjussojpsvncnjghyrft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqdXNzb2pwc3ZuY25qZ2h5cmZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NjA5MTUsImV4cCI6MjA2NjQzNjkxNX0.QAV3YU9dorPLtOimpq7u9UgdJM0IGMzMp_uaTuoeSPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);